### ISSUE TITLE
Fix warning with "useNativeDriver Warning"

### ISSUE THREAD

**Issue by farzanehfar** [ideafast/ideafast-patientapp#17]

**Comment by farzanehfar** [comment]
find RCTAnimation.xcodeproj The file can be found from node_modules/react-native/NativeAnimation OR node_modules/react-native/Libraries/NativeAnimation
open xcode
open project navigator (press cmd + 1 OR click folder icon from the left)
drag & drop RCTAnimation.xcodeproj from the previous step to Libraries folder
Expand RCTAnimation.xcodeproj in project navigator and find libRCTAnimation.a file inside of Products folder
click on your project name on top of project navigator and go to Build Phrases tab
drag and drop libRCTAnimation.a to Link Binary With Libraries
Clean and run..

**Comment by jawrainey** [comment]
Closed in #52
