### ISSUE TITLE
Implement Help and Profile Tabs

### ISSUE THREAD

**Issue by drewmiley** [ideafast/ideafast-patientapp#2]
As detailed in these screenshots - https://xd.adobe.com/view/cc9640fb-7dc6-4886-46c3-f9324e81f8a4-baa7/grid/ (HELP, HELP-1, HELP-2)

Potential Screen/Container names - 
HelpDeviceList
HelpDeviceQuestions
HelpQuestion

This will likely involve work passing params to routes https://reactnavigation.org/docs/params in order to determine correct device, correct question etc.

**Comment by farzanehfar** [comment]
Added the following Containers to the Help tab:

FAQ: the patient should be able to find their questions
About devices: all questions about only devices
Contact us: if patient can not find the answers, they can contact by email, phone numbers(?)

**Comment by farzanehfar** [comment]
Added the following to the Profile tab:

A profile avatar image
User's Id number: It will display below the avatar image
Sign out: When the user sign out, it should redirect to the welcome/signIn screen

**Comment by farzanehfar** [comment]
This branch can be as a skeleton (JUST Skeleton), as Drew is going to start working on sign in/welcome screen, he can make a new branch out of master with these new changes.

Please keep those in mind in review: I have not completed :

* Headers
* the contents of 3 pages for help
* There is no welcome/sign screen
* Icons are not completed yet as I have created another branch for styles of the bottom tab
* Sig out button is not implemented as It needs signIn screen
