### ISSUE TITLE
Implement structure for internationalisation of string

### ISSUE THREAD

**Issue by drewmiley** [ideafast/ideafast-patientapp#43]
- [x] Assigned a **Project** to the issue.
- [ ] Assigned a potential **assignee**.

**Is this feature related to a current problem? Please describe.**

Internationalisation is best done early in the project when number of strings is manageable.

**Describe the feature**

The app will need to work in multiple languages. To facilitate this, we need to offer string translations.

**Testing Criteria**

String can be varied based on language selection (this could be internal for now?)

**Comment by jawrainey** [comment]
I'm happy to pick this up and [i18next](https://react.i18next.com/) seems suitable as it's actively developed and (seems to be) straight forward to use.

Re:testing -> we should add a German translation for all current string files (translated by Google Translate for now) to have the file structure and logic in place for multiple languages. The logic to switch between languages (based on either/and (i) users device language; or (ii) their choice in our app) can be [unit tested](https://react.i18next.com/misc/testing). 

Given our 'Settings' page doesn't yet exist where the user can switch languages, I think it would be fine to unit test this logic for now?

**Comment by NNowakowski** [comment]
I've stumbled upon this issue while browsing GitHub for translation tasks and could provide you with german translations once you've got the necessary structure implemented
