### ISSUE TITLE
Global styles structure

### ISSUE THREAD

**Issue by drewmiley** [ideafast/ideafast-patientapp#44]
- [x] Assigned a **Project** to the issue.
- [ ] Assigned a potential **assignee**.

**Is this feature related to a current problem? Please describe.**

Currently styles are fairly haphazardly applied. We need a uniform approach.

**Describe the feature**

Implement a global structure for styles that is extendable, manageable, and easy to understand.

**Testing Criteria**

Styles should still work, and be intuitive to alter.

**Comment by jawrainey** [comment]
@farzanehfar resolved this in PR #47
