### ISSUE TITLE
Profile's Text Input is not updated by a suitable "User Id" in master branch

### ISSUE THREAD

**Issue by farzanehfar** [ideafast/ideafast-patientapp#46]
- [x] Assigned a **Project** to the issue.
- [ ] Assigned a potential **assignee**.

**Describe the bug**
1. Enter a User Id in verify screen
2. Press Verify button
3. Expected: The profile's text input updated by a proper User Id.

**How can it be reproduced?**
See the steps

**Which device(s) are impacted? **

No impact at this moment

**Comment by jawrainey** [comment]
Closing as the Settings page now shows the user's ID based on the MOCK data. The verification screen will take a one-time generated token in the future to verify participants, which won't be reused/displayed in the app.
