### ISSUE TITLE
Contact Information

### ISSUE THREAD

**Issue by farzanehfar** [ideafast/ideafast-patientapp#9]

**Comment by jawrainey** [comment]
This screen is currently in [Help->ContactUs](https://github.com/ideafast/ideafast-patientapp/blob/8641174468c3078f1dadafe034ef44a50f9f0b93/src/containers/ContactUs.js) with placeholder text.

@farzanehfar -- "Contact Us" should be named "Study Center Contact Details" to remove ambiguity as it is unclear who is "us". I am also not certain if we should include contact details in the application? 

The study will cover four _study centres_. The contact us page should display specific data for each study centres. Participants should only be able to contact a person they know from the study center. We do not have those details yet, but have outlined the table below as placeholder in our documents:

Newcastle, United Kingdom | Rotterdam, Netherlands | Kiel, Germany | Münster, Germany
-- | -- | -- | --
Person Name, Centre Name, Location | Person Name, Centre Name, Location | Person Name, Centre Name, Location | Person Name, Centre Name, Location
